### ISSUE TITLE
Improve parameters to configure AWS Organization

### ISSUE THREAD

**Issue by 92nqb** [cloud-toolkit/cloud-toolkit-aws#33]
To import an Organization, setting up the same parameters with the same values is mandatory. It is required to add more and better parameters to config an organization like:

- awsServiceAccessPrincipals
- enabledPolicyTypes
- featureSet

**Comment by pasqualet** [comment]
Those parameters can produce a bug when importing an existing AWS Organization. If we import an Organization with an empty array for the `awsServiceAccessPrincipals` or `enabledPolicyTypes` parameter, the AWS Organization can't be imported.
