### ISSUE TITLE
Add ClusterAutoscaler component in Kubernetes Cluster

### ISSUE THREAD

**Issue by pasqualet** [cloud-toolkit/cloud-toolkit-aws#38]
### What would you like to be added?

Add ClusterAutoscaler component in Kubernetes Cluster.

### Why is this needed?

Users want Kubernetes Clusters to autoscale according to application load.

**Comment by bernardomp** [comment]
Ready to make PR with this code: https://github.com/bernardomp/cloud-toolkit-aws/tree/kubernetes-addons
